Working
BSGreaves/sandwichmaker pull request #1
Opened 2017-02-20 22:14 UTC by BSGreaves

@drdreed Sandwich Maker ready for feedback.

I deviated from the letter (but not the spirit) of the assignment in once instance:
"Each IIFE should expose, in its public interface, a method named add{ingredient} (e.g. addMeat or addVeggies) that accepts a single argument. That argument's value should be the ingredient selected by the user."
My "add ingredients" functions actually take 2 inputs - the ingredient name,  and also whether the user checked or unchecked the box.  That way, it actively updates the final price whenever a checkbox is checked or unchecked. It seemed easier than adding a separate "remove ingredient" function in each IIFE augmenter (which is not included in the instructions).
Thanks

2017-02-20 22:24 UTC, DevDreed requested changes
Just a couple of changes to clean up the code base.  Looking good though.

2017-02-20 22:24 UTC, drdreed commented on js/bread.js
> +		}
You could do an else here.  Boolean's can only have two values.  So its either true or false.

2017-02-20 22:24 UTC, drdreed commented on js/cheese.js
> +		}
Same thing here.  Could use an else statement.

2017-02-20 22:24 UTC, drdreed commented on js/condiments.js
> +		}
Could use an else statement here as well.

2017-02-20 22:24 UTC, drdreed commented on js/meats.js
> +		}
Else statement here as well.

2017-02-20 22:24 UTC, drdreed commented on js/veggies.js
> +		}
And again and else statement.

2017-02-21 00:05 UTC, DevDreed approved these changes
👍

2017-02-21 00:05 UTC, BSGreaves commented
Good catches, thanks! Changes made.

2017-02-21 02:12 UTC, merged